-- create
create table public.todos (
  id bigint generated by default as identity primary key,
  name text not null,
  done boolean not null default false,
  created_at timestamp with time zone not null default now()
);

-- pupulate
insert into public.todos (name, done)
values
  ('Buy groceries', false),
  ('Finish project notes', false),
  ('Review completed task', true);

-- delete
drop table public.todos;
