/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryFlowIndexRouteImport } from './routes/story-flow/index'
import { Route as TestTodoRouteImport } from './routes/test/todo'
import { Route as ApiStoriesRouteImport } from './routes/api/stories'
import { Route as StoryFlowonboardingProblemRouteImport } from './routes/story-flow/(onboarding)/problem'
import { Route as StoryFlowonboardingNameRouteImport } from './routes/story-flow/(onboarding)/name'
import { Route as StoryFlowonboardingGoalRouteImport } from './routes/story-flow/(onboarding)/goal'
import { Route as StoryFlowonboardingBlurbRouteImport } from './routes/story-flow/(onboarding)/blurb'
import { Route as ApiStoriesStoryIdRouteImport } from './routes/api/stories/$storyId'
import { Route as ApiQuestsQuestIdRouteImport } from './routes/api/quests/$questId'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate/image'
import { Route as ApiGenerateDataRouteImport } from './routes/api/generate/data'
import { Route as ApiStoriesStoryIdSessionRouteImport } from './routes/api/stories/$storyId/session'
import { Route as ApiStoriesStoryIdQuestsRouteImport } from './routes/api/stories/$storyId/quests'
import { Route as ApiQuestsQuestIdCompleteRouteImport } from './routes/api/quests/$questId/complete'
import { Route as ApiQuestsQuestIdAcceptRouteImport } from './routes/api/quests/$questId/accept'
import { Route as StoryFlowpersistedStoriesStoryIdIndexRouteImport } from './routes/story-flow/(persisted)/stories/$storyId/index'
import { Route as StoryFlowpersistedStoriesStoryIdBlurbRouteImport } from './routes/story-flow/(persisted)/stories/$storyId/blurb'
import { Route as StoryFlowpersistedStoriesStoryIdQuestProposalRouteImport } from './routes/story-flow/(persisted)/stories/$storyId/quest/proposal'
import { Route as StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRouteImport } from './routes/story-flow/(persisted)/stories/$storyId/quest/$questId/result'
import { Route as StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRouteImport } from './routes/story-flow/(persisted)/stories/$storyId/quest/$questId/feedback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowIndexRoute = StoryFlowIndexRouteImport.update({
  id: '/story-flow/',
  path: '/story-flow/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTodoRoute = TestTodoRouteImport.update({
  id: '/test/todo',
  path: '/test/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesRoute = ApiStoriesRouteImport.update({
  id: '/api/stories',
  path: '/api/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowonboardingProblemRoute =
  StoryFlowonboardingProblemRouteImport.update({
    id: '/story-flow/(onboarding)/problem',
    path: '/story-flow/problem',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowonboardingNameRoute = StoryFlowonboardingNameRouteImport.update({
  id: '/story-flow/(onboarding)/name',
  path: '/story-flow/name',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowonboardingGoalRoute = StoryFlowonboardingGoalRouteImport.update({
  id: '/story-flow/(onboarding)/goal',
  path: '/story-flow/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowonboardingBlurbRoute =
  StoryFlowonboardingBlurbRouteImport.update({
    id: '/story-flow/(onboarding)/blurb',
    path: '/story-flow/blurb',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStoriesStoryIdRoute = ApiStoriesStoryIdRouteImport.update({
  id: '/$storyId',
  path: '/$storyId',
  getParentRoute: () => ApiStoriesRoute,
} as any)
const ApiQuestsQuestIdRoute = ApiQuestsQuestIdRouteImport.update({
  id: '/api/quests/$questId',
  path: '/api/quests/$questId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate/image',
  path: '/api/generate/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateDataRoute = ApiGenerateDataRouteImport.update({
  id: '/api/generate/data',
  path: '/api/generate/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoriesStoryIdSessionRoute =
  ApiStoriesStoryIdSessionRouteImport.update({
    id: '/session',
    path: '/session',
    getParentRoute: () => ApiStoriesStoryIdRoute,
  } as any)
const ApiStoriesStoryIdQuestsRoute = ApiStoriesStoryIdQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => ApiStoriesStoryIdRoute,
} as any)
const ApiQuestsQuestIdCompleteRoute =
  ApiQuestsQuestIdCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiQuestsQuestIdRoute,
  } as any)
const ApiQuestsQuestIdAcceptRoute = ApiQuestsQuestIdAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => ApiQuestsQuestIdRoute,
} as any)
const StoryFlowpersistedStoriesStoryIdIndexRoute =
  StoryFlowpersistedStoriesStoryIdIndexRouteImport.update({
    id: '/story-flow/(persisted)/stories/$storyId/',
    path: '/story-flow/stories/$storyId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowpersistedStoriesStoryIdBlurbRoute =
  StoryFlowpersistedStoriesStoryIdBlurbRouteImport.update({
    id: '/story-flow/(persisted)/stories/$storyId/blurb',
    path: '/story-flow/stories/$storyId/blurb',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowpersistedStoriesStoryIdQuestProposalRoute =
  StoryFlowpersistedStoriesStoryIdQuestProposalRouteImport.update({
    id: '/story-flow/(persisted)/stories/$storyId/quest/proposal',
    path: '/story-flow/stories/$storyId/quest/proposal',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute =
  StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRouteImport.update({
    id: '/story-flow/(persisted)/stories/$storyId/quest/$questId/result',
    path: '/story-flow/stories/$storyId/quest/$questId/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute =
  StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRouteImport.update({
    id: '/story-flow/(persisted)/stories/$storyId/quest/$questId/feedback',
    path: '/story-flow/stories/$storyId/quest/$questId/feedback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/test/todo': typeof TestTodoRoute
  '/story-flow/': typeof StoryFlowIndexRoute
  '/api/generate/data': typeof ApiGenerateDataRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/quests/$questId': typeof ApiQuestsQuestIdRouteWithChildren
  '/api/stories/$storyId': typeof ApiStoriesStoryIdRouteWithChildren
  '/story-flow/blurb': typeof StoryFlowonboardingBlurbRoute
  '/story-flow/goal': typeof StoryFlowonboardingGoalRoute
  '/story-flow/name': typeof StoryFlowonboardingNameRoute
  '/story-flow/problem': typeof StoryFlowonboardingProblemRoute
  '/api/quests/$questId/accept': typeof ApiQuestsQuestIdAcceptRoute
  '/api/quests/$questId/complete': typeof ApiQuestsQuestIdCompleteRoute
  '/api/stories/$storyId/quests': typeof ApiStoriesStoryIdQuestsRoute
  '/api/stories/$storyId/session': typeof ApiStoriesStoryIdSessionRoute
  '/story-flow/stories/$storyId/blurb': typeof StoryFlowpersistedStoriesStoryIdBlurbRoute
  '/story-flow/stories/$storyId/': typeof StoryFlowpersistedStoriesStoryIdIndexRoute
  '/story-flow/stories/$storyId/quest/proposal': typeof StoryFlowpersistedStoriesStoryIdQuestProposalRoute
  '/story-flow/stories/$storyId/quest/$questId/feedback': typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute
  '/story-flow/stories/$storyId/quest/$questId/result': typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/test/todo': typeof TestTodoRoute
  '/story-flow': typeof StoryFlowIndexRoute
  '/api/generate/data': typeof ApiGenerateDataRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/quests/$questId': typeof ApiQuestsQuestIdRouteWithChildren
  '/api/stories/$storyId': typeof ApiStoriesStoryIdRouteWithChildren
  '/story-flow/blurb': typeof StoryFlowonboardingBlurbRoute
  '/story-flow/goal': typeof StoryFlowonboardingGoalRoute
  '/story-flow/name': typeof StoryFlowonboardingNameRoute
  '/story-flow/problem': typeof StoryFlowonboardingProblemRoute
  '/api/quests/$questId/accept': typeof ApiQuestsQuestIdAcceptRoute
  '/api/quests/$questId/complete': typeof ApiQuestsQuestIdCompleteRoute
  '/api/stories/$storyId/quests': typeof ApiStoriesStoryIdQuestsRoute
  '/api/stories/$storyId/session': typeof ApiStoriesStoryIdSessionRoute
  '/story-flow/stories/$storyId/blurb': typeof StoryFlowpersistedStoriesStoryIdBlurbRoute
  '/story-flow/stories/$storyId': typeof StoryFlowpersistedStoriesStoryIdIndexRoute
  '/story-flow/stories/$storyId/quest/proposal': typeof StoryFlowpersistedStoriesStoryIdQuestProposalRoute
  '/story-flow/stories/$storyId/quest/$questId/feedback': typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute
  '/story-flow/stories/$storyId/quest/$questId/result': typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/stories': typeof ApiStoriesRouteWithChildren
  '/test/todo': typeof TestTodoRoute
  '/story-flow/': typeof StoryFlowIndexRoute
  '/api/generate/data': typeof ApiGenerateDataRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/api/quests/$questId': typeof ApiQuestsQuestIdRouteWithChildren
  '/api/stories/$storyId': typeof ApiStoriesStoryIdRouteWithChildren
  '/story-flow/(onboarding)/blurb': typeof StoryFlowonboardingBlurbRoute
  '/story-flow/(onboarding)/goal': typeof StoryFlowonboardingGoalRoute
  '/story-flow/(onboarding)/name': typeof StoryFlowonboardingNameRoute
  '/story-flow/(onboarding)/problem': typeof StoryFlowonboardingProblemRoute
  '/api/quests/$questId/accept': typeof ApiQuestsQuestIdAcceptRoute
  '/api/quests/$questId/complete': typeof ApiQuestsQuestIdCompleteRoute
  '/api/stories/$storyId/quests': typeof ApiStoriesStoryIdQuestsRoute
  '/api/stories/$storyId/session': typeof ApiStoriesStoryIdSessionRoute
  '/story-flow/(persisted)/stories/$storyId/blurb': typeof StoryFlowpersistedStoriesStoryIdBlurbRoute
  '/story-flow/(persisted)/stories/$storyId/': typeof StoryFlowpersistedStoriesStoryIdIndexRoute
  '/story-flow/(persisted)/stories/$storyId/quest/proposal': typeof StoryFlowpersistedStoriesStoryIdQuestProposalRoute
  '/story-flow/(persisted)/stories/$storyId/quest/$questId/feedback': typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute
  '/story-flow/(persisted)/stories/$storyId/quest/$questId/result': typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/stories'
    | '/test/todo'
    | '/story-flow/'
    | '/api/generate/data'
    | '/api/generate/image'
    | '/api/quests/$questId'
    | '/api/stories/$storyId'
    | '/story-flow/blurb'
    | '/story-flow/goal'
    | '/story-flow/name'
    | '/story-flow/problem'
    | '/api/quests/$questId/accept'
    | '/api/quests/$questId/complete'
    | '/api/stories/$storyId/quests'
    | '/api/stories/$storyId/session'
    | '/story-flow/stories/$storyId/blurb'
    | '/story-flow/stories/$storyId/'
    | '/story-flow/stories/$storyId/quest/proposal'
    | '/story-flow/stories/$storyId/quest/$questId/feedback'
    | '/story-flow/stories/$storyId/quest/$questId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/stories'
    | '/test/todo'
    | '/story-flow'
    | '/api/generate/data'
    | '/api/generate/image'
    | '/api/quests/$questId'
    | '/api/stories/$storyId'
    | '/story-flow/blurb'
    | '/story-flow/goal'
    | '/story-flow/name'
    | '/story-flow/problem'
    | '/api/quests/$questId/accept'
    | '/api/quests/$questId/complete'
    | '/api/stories/$storyId/quests'
    | '/api/stories/$storyId/session'
    | '/story-flow/stories/$storyId/blurb'
    | '/story-flow/stories/$storyId'
    | '/story-flow/stories/$storyId/quest/proposal'
    | '/story-flow/stories/$storyId/quest/$questId/feedback'
    | '/story-flow/stories/$storyId/quest/$questId/result'
  id:
    | '__root__'
    | '/'
    | '/api/stories'
    | '/test/todo'
    | '/story-flow/'
    | '/api/generate/data'
    | '/api/generate/image'
    | '/api/quests/$questId'
    | '/api/stories/$storyId'
    | '/story-flow/(onboarding)/blurb'
    | '/story-flow/(onboarding)/goal'
    | '/story-flow/(onboarding)/name'
    | '/story-flow/(onboarding)/problem'
    | '/api/quests/$questId/accept'
    | '/api/quests/$questId/complete'
    | '/api/stories/$storyId/quests'
    | '/api/stories/$storyId/session'
    | '/story-flow/(persisted)/stories/$storyId/blurb'
    | '/story-flow/(persisted)/stories/$storyId/'
    | '/story-flow/(persisted)/stories/$storyId/quest/proposal'
    | '/story-flow/(persisted)/stories/$storyId/quest/$questId/feedback'
    | '/story-flow/(persisted)/stories/$storyId/quest/$questId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiStoriesRoute: typeof ApiStoriesRouteWithChildren
  TestTodoRoute: typeof TestTodoRoute
  StoryFlowIndexRoute: typeof StoryFlowIndexRoute
  ApiGenerateDataRoute: typeof ApiGenerateDataRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiQuestsQuestIdRoute: typeof ApiQuestsQuestIdRouteWithChildren
  StoryFlowonboardingBlurbRoute: typeof StoryFlowonboardingBlurbRoute
  StoryFlowonboardingGoalRoute: typeof StoryFlowonboardingGoalRoute
  StoryFlowonboardingNameRoute: typeof StoryFlowonboardingNameRoute
  StoryFlowonboardingProblemRoute: typeof StoryFlowonboardingProblemRoute
  StoryFlowpersistedStoriesStoryIdBlurbRoute: typeof StoryFlowpersistedStoriesStoryIdBlurbRoute
  StoryFlowpersistedStoriesStoryIdIndexRoute: typeof StoryFlowpersistedStoriesStoryIdIndexRoute
  StoryFlowpersistedStoriesStoryIdQuestProposalRoute: typeof StoryFlowpersistedStoriesStoryIdQuestProposalRoute
  StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute: typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute
  StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute: typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/': {
      id: '/story-flow/'
      path: '/story-flow'
      fullPath: '/story-flow/'
      preLoaderRoute: typeof StoryFlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/todo': {
      id: '/test/todo'
      path: '/test/todo'
      fullPath: '/test/todo'
      preLoaderRoute: typeof TestTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories': {
      id: '/api/stories'
      path: '/api/stories'
      fullPath: '/api/stories'
      preLoaderRoute: typeof ApiStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/problem': {
      id: '/story-flow/(onboarding)/problem'
      path: '/story-flow/problem'
      fullPath: '/story-flow/problem'
      preLoaderRoute: typeof StoryFlowonboardingProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/name': {
      id: '/story-flow/(onboarding)/name'
      path: '/story-flow/name'
      fullPath: '/story-flow/name'
      preLoaderRoute: typeof StoryFlowonboardingNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/goal': {
      id: '/story-flow/(onboarding)/goal'
      path: '/story-flow/goal'
      fullPath: '/story-flow/goal'
      preLoaderRoute: typeof StoryFlowonboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/blurb': {
      id: '/story-flow/(onboarding)/blurb'
      path: '/story-flow/blurb'
      fullPath: '/story-flow/blurb'
      preLoaderRoute: typeof StoryFlowonboardingBlurbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$storyId': {
      id: '/api/stories/$storyId'
      path: '/$storyId'
      fullPath: '/api/stories/$storyId'
      preLoaderRoute: typeof ApiStoriesStoryIdRouteImport
      parentRoute: typeof ApiStoriesRoute
    }
    '/api/quests/$questId': {
      id: '/api/quests/$questId'
      path: '/api/quests/$questId'
      fullPath: '/api/quests/$questId'
      preLoaderRoute: typeof ApiQuestsQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/image': {
      id: '/api/generate/image'
      path: '/api/generate/image'
      fullPath: '/api/generate/image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/data': {
      id: '/api/generate/data'
      path: '/api/generate/data'
      fullPath: '/api/generate/data'
      preLoaderRoute: typeof ApiGenerateDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stories/$storyId/session': {
      id: '/api/stories/$storyId/session'
      path: '/session'
      fullPath: '/api/stories/$storyId/session'
      preLoaderRoute: typeof ApiStoriesStoryIdSessionRouteImport
      parentRoute: typeof ApiStoriesStoryIdRoute
    }
    '/api/stories/$storyId/quests': {
      id: '/api/stories/$storyId/quests'
      path: '/quests'
      fullPath: '/api/stories/$storyId/quests'
      preLoaderRoute: typeof ApiStoriesStoryIdQuestsRouteImport
      parentRoute: typeof ApiStoriesStoryIdRoute
    }
    '/api/quests/$questId/complete': {
      id: '/api/quests/$questId/complete'
      path: '/complete'
      fullPath: '/api/quests/$questId/complete'
      preLoaderRoute: typeof ApiQuestsQuestIdCompleteRouteImport
      parentRoute: typeof ApiQuestsQuestIdRoute
    }
    '/api/quests/$questId/accept': {
      id: '/api/quests/$questId/accept'
      path: '/accept'
      fullPath: '/api/quests/$questId/accept'
      preLoaderRoute: typeof ApiQuestsQuestIdAcceptRouteImport
      parentRoute: typeof ApiQuestsQuestIdRoute
    }
    '/story-flow/(persisted)/stories/$storyId/': {
      id: '/story-flow/(persisted)/stories/$storyId/'
      path: '/story-flow/stories/$storyId'
      fullPath: '/story-flow/stories/$storyId/'
      preLoaderRoute: typeof StoryFlowpersistedStoriesStoryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(persisted)/stories/$storyId/blurb': {
      id: '/story-flow/(persisted)/stories/$storyId/blurb'
      path: '/story-flow/stories/$storyId/blurb'
      fullPath: '/story-flow/stories/$storyId/blurb'
      preLoaderRoute: typeof StoryFlowpersistedStoriesStoryIdBlurbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(persisted)/stories/$storyId/quest/proposal': {
      id: '/story-flow/(persisted)/stories/$storyId/quest/proposal'
      path: '/story-flow/stories/$storyId/quest/proposal'
      fullPath: '/story-flow/stories/$storyId/quest/proposal'
      preLoaderRoute: typeof StoryFlowpersistedStoriesStoryIdQuestProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(persisted)/stories/$storyId/quest/$questId/result': {
      id: '/story-flow/(persisted)/stories/$storyId/quest/$questId/result'
      path: '/story-flow/stories/$storyId/quest/$questId/result'
      fullPath: '/story-flow/stories/$storyId/quest/$questId/result'
      preLoaderRoute: typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(persisted)/stories/$storyId/quest/$questId/feedback': {
      id: '/story-flow/(persisted)/stories/$storyId/quest/$questId/feedback'
      path: '/story-flow/stories/$storyId/quest/$questId/feedback'
      fullPath: '/story-flow/stories/$storyId/quest/$questId/feedback'
      preLoaderRoute: typeof StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiStoriesStoryIdRouteChildren {
  ApiStoriesStoryIdQuestsRoute: typeof ApiStoriesStoryIdQuestsRoute
  ApiStoriesStoryIdSessionRoute: typeof ApiStoriesStoryIdSessionRoute
}

const ApiStoriesStoryIdRouteChildren: ApiStoriesStoryIdRouteChildren = {
  ApiStoriesStoryIdQuestsRoute: ApiStoriesStoryIdQuestsRoute,
  ApiStoriesStoryIdSessionRoute: ApiStoriesStoryIdSessionRoute,
}

const ApiStoriesStoryIdRouteWithChildren =
  ApiStoriesStoryIdRoute._addFileChildren(ApiStoriesStoryIdRouteChildren)

interface ApiStoriesRouteChildren {
  ApiStoriesStoryIdRoute: typeof ApiStoriesStoryIdRouteWithChildren
}

const ApiStoriesRouteChildren: ApiStoriesRouteChildren = {
  ApiStoriesStoryIdRoute: ApiStoriesStoryIdRouteWithChildren,
}

const ApiStoriesRouteWithChildren = ApiStoriesRoute._addFileChildren(
  ApiStoriesRouteChildren,
)

interface ApiQuestsQuestIdRouteChildren {
  ApiQuestsQuestIdAcceptRoute: typeof ApiQuestsQuestIdAcceptRoute
  ApiQuestsQuestIdCompleteRoute: typeof ApiQuestsQuestIdCompleteRoute
}

const ApiQuestsQuestIdRouteChildren: ApiQuestsQuestIdRouteChildren = {
  ApiQuestsQuestIdAcceptRoute: ApiQuestsQuestIdAcceptRoute,
  ApiQuestsQuestIdCompleteRoute: ApiQuestsQuestIdCompleteRoute,
}

const ApiQuestsQuestIdRouteWithChildren =
  ApiQuestsQuestIdRoute._addFileChildren(ApiQuestsQuestIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiStoriesRoute: ApiStoriesRouteWithChildren,
  TestTodoRoute: TestTodoRoute,
  StoryFlowIndexRoute: StoryFlowIndexRoute,
  ApiGenerateDataRoute: ApiGenerateDataRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiQuestsQuestIdRoute: ApiQuestsQuestIdRouteWithChildren,
  StoryFlowonboardingBlurbRoute: StoryFlowonboardingBlurbRoute,
  StoryFlowonboardingGoalRoute: StoryFlowonboardingGoalRoute,
  StoryFlowonboardingNameRoute: StoryFlowonboardingNameRoute,
  StoryFlowonboardingProblemRoute: StoryFlowonboardingProblemRoute,
  StoryFlowpersistedStoriesStoryIdBlurbRoute:
    StoryFlowpersistedStoriesStoryIdBlurbRoute,
  StoryFlowpersistedStoriesStoryIdIndexRoute:
    StoryFlowpersistedStoriesStoryIdIndexRoute,
  StoryFlowpersistedStoriesStoryIdQuestProposalRoute:
    StoryFlowpersistedStoriesStoryIdQuestProposalRoute,
  StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute:
    StoryFlowpersistedStoriesStoryIdQuestQuestIdFeedbackRoute,
  StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute:
    StoryFlowpersistedStoriesStoryIdQuestQuestIdResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
