/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteRouteImport } from './routes/test/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoryFlowIndexRouteImport } from './routes/story-flow/index'
import { Route as ApiTestRouteRouteImport } from './routes/api/test/route'
import { Route as StoryFlowonboardingStoryRouteImport } from './routes/story-flow/(onboarding)/story'
import { Route as StoryFlowonboardingProblemRouteImport } from './routes/story-flow/(onboarding)/problem'
import { Route as StoryFlowonboardingNameRouteImport } from './routes/story-flow/(onboarding)/name'
import { Route as StoryFlowonboardingGoalRouteImport } from './routes/story-flow/(onboarding)/goal'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate/image'
import { Route as ApiGenerateDataRouteImport } from './routes/api/generate/data'

const TestRouteRoute = TestRouteRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowIndexRoute = StoryFlowIndexRouteImport.update({
  id: '/story-flow/',
  path: '/story-flow/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRouteRoute = ApiTestRouteRouteImport.update({
  id: '/api/test',
  path: '/api/test',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowonboardingStoryRoute =
  StoryFlowonboardingStoryRouteImport.update({
    id: '/story-flow/(onboarding)/story',
    path: '/story-flow/story',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowonboardingProblemRoute =
  StoryFlowonboardingProblemRouteImport.update({
    id: '/story-flow/(onboarding)/problem',
    path: '/story-flow/problem',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoryFlowonboardingNameRoute = StoryFlowonboardingNameRouteImport.update({
  id: '/story-flow/(onboarding)/name',
  path: '/story-flow/name',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryFlowonboardingGoalRoute = StoryFlowonboardingGoalRouteImport.update({
  id: '/story-flow/(onboarding)/goal',
  path: '/story-flow/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate/image',
  path: '/api/generate/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateDataRoute = ApiGenerateDataRouteImport.update({
  id: '/api/generate/data',
  path: '/api/generate/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRouteRoute
  '/api/test': typeof ApiTestRouteRoute
  '/story-flow/': typeof StoryFlowIndexRoute
  '/api/generate/data': typeof ApiGenerateDataRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/story-flow/goal': typeof StoryFlowonboardingGoalRoute
  '/story-flow/name': typeof StoryFlowonboardingNameRoute
  '/story-flow/problem': typeof StoryFlowonboardingProblemRoute
  '/story-flow/story': typeof StoryFlowonboardingStoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRouteRoute
  '/api/test': typeof ApiTestRouteRoute
  '/story-flow': typeof StoryFlowIndexRoute
  '/api/generate/data': typeof ApiGenerateDataRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/story-flow/goal': typeof StoryFlowonboardingGoalRoute
  '/story-flow/name': typeof StoryFlowonboardingNameRoute
  '/story-flow/problem': typeof StoryFlowonboardingProblemRoute
  '/story-flow/story': typeof StoryFlowonboardingStoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRouteRoute
  '/api/test': typeof ApiTestRouteRoute
  '/story-flow/': typeof StoryFlowIndexRoute
  '/api/generate/data': typeof ApiGenerateDataRoute
  '/api/generate/image': typeof ApiGenerateImageRoute
  '/story-flow/(onboarding)/goal': typeof StoryFlowonboardingGoalRoute
  '/story-flow/(onboarding)/name': typeof StoryFlowonboardingNameRoute
  '/story-flow/(onboarding)/problem': typeof StoryFlowonboardingProblemRoute
  '/story-flow/(onboarding)/story': typeof StoryFlowonboardingStoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/api/test'
    | '/story-flow/'
    | '/api/generate/data'
    | '/api/generate/image'
    | '/story-flow/goal'
    | '/story-flow/name'
    | '/story-flow/problem'
    | '/story-flow/story'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/api/test'
    | '/story-flow'
    | '/api/generate/data'
    | '/api/generate/image'
    | '/story-flow/goal'
    | '/story-flow/name'
    | '/story-flow/problem'
    | '/story-flow/story'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/api/test'
    | '/story-flow/'
    | '/api/generate/data'
    | '/api/generate/image'
    | '/story-flow/(onboarding)/goal'
    | '/story-flow/(onboarding)/name'
    | '/story-flow/(onboarding)/problem'
    | '/story-flow/(onboarding)/story'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRouteRoute: typeof TestRouteRoute
  ApiTestRouteRoute: typeof ApiTestRouteRoute
  StoryFlowIndexRoute: typeof StoryFlowIndexRoute
  ApiGenerateDataRoute: typeof ApiGenerateDataRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  StoryFlowonboardingGoalRoute: typeof StoryFlowonboardingGoalRoute
  StoryFlowonboardingNameRoute: typeof StoryFlowonboardingNameRoute
  StoryFlowonboardingProblemRoute: typeof StoryFlowonboardingProblemRoute
  StoryFlowonboardingStoryRoute: typeof StoryFlowonboardingStoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/': {
      id: '/story-flow/'
      path: '/story-flow'
      fullPath: '/story-flow/'
      preLoaderRoute: typeof StoryFlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test': {
      id: '/api/test'
      path: '/api/test'
      fullPath: '/api/test'
      preLoaderRoute: typeof ApiTestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/story': {
      id: '/story-flow/(onboarding)/story'
      path: '/story-flow/story'
      fullPath: '/story-flow/story'
      preLoaderRoute: typeof StoryFlowonboardingStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/problem': {
      id: '/story-flow/(onboarding)/problem'
      path: '/story-flow/problem'
      fullPath: '/story-flow/problem'
      preLoaderRoute: typeof StoryFlowonboardingProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/name': {
      id: '/story-flow/(onboarding)/name'
      path: '/story-flow/name'
      fullPath: '/story-flow/name'
      preLoaderRoute: typeof StoryFlowonboardingNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-flow/(onboarding)/goal': {
      id: '/story-flow/(onboarding)/goal'
      path: '/story-flow/goal'
      fullPath: '/story-flow/goal'
      preLoaderRoute: typeof StoryFlowonboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/image': {
      id: '/api/generate/image'
      path: '/api/generate/image'
      fullPath: '/api/generate/image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/data': {
      id: '/api/generate/data'
      path: '/api/generate/data'
      fullPath: '/api/generate/data'
      preLoaderRoute: typeof ApiGenerateDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRouteRoute: TestRouteRoute,
  ApiTestRouteRoute: ApiTestRouteRoute,
  StoryFlowIndexRoute: StoryFlowIndexRoute,
  ApiGenerateDataRoute: ApiGenerateDataRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  StoryFlowonboardingGoalRoute: StoryFlowonboardingGoalRoute,
  StoryFlowonboardingNameRoute: StoryFlowonboardingNameRoute,
  StoryFlowonboardingProblemRoute: StoryFlowonboardingProblemRoute,
  StoryFlowonboardingStoryRoute: StoryFlowonboardingStoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
